### ISSUE TITLE
Feature request: word count

### ISSUE THREAD

**Issue by claudioruiz** [notaapp/nota#114]
There's a really cool feature on iaWriter that shows you the number of words / characters / characters with spaces / sentences / reading time that is really useful for writing documentation that has a word or character limit. It would be really cool to implement something like that.

**Comment by astoilkov** [comment]
We have such an experiment under Preferences → Labs → Text Stats. You can turn it on and you should see a word count in the bottom right corner. Note that it's an experiment because it slows down typing a little in big documents.

**Comment by claudioruiz** [comment]
this is brilliant. Let me say that I love this app so much.

**Comment by astoilkov** [comment]
Wow. Thanks! What do you use it for?

**Comment by claudioruiz** [comment]
> Wow. Thanks! What do you use it for?

Do you mean the app or the word count? I'm testing the app as a plain text replacement of google drive/docs using NextCloud as a backend. :¨)

A killer feature, although maybe it's far beyond of the project, might be to implement some team-sharing features in-app.

**Comment by astoilkov** [comment]
> Do you mean the app or the word count? I'm testing the app as a plain text replacement of google drive/docs using NextCloud as a backend. :¨)

I meant the app. Thanks. Great to hear you are trying to transition to plain text.

> A killer feature, although maybe it's far beyond of the project, might be to implement some team-sharing features in-app.

We are thinking about a more integrated Git support for teams. Is this something that will work for you?

**Comment by claudioruiz** [comment]
Oh, I already transitioned to plain text files ages ago! ;) 

What I meant is to have a sync backend (I need to test it further, but so far I've been using nextcloud for that), and a way to work simultaneously with more than one user at a time, more or less as to what etherpad lite does.

So, idk about the technical details of it (whereas is a git-based model or not), but that is what is needed for having an alternative to gdrive/docs and or MS Word for teams (meaning editing a text in collaboration).

In any event, Nota this is one of my most used apps since I discovered it.

**Comment by astoilkov** [comment]
Great. Thanks for the detailed explanation.

> In any event, Nota this is one of my most used apps since I discovered it.

😍

**Comment by astoilkov** [comment]
I will close this issue as this is available as an experiment. Thanks for all the details and information about your usage!

**Comment by erusev** [comment]
@petrbouchal thanks for sharing your thoughts on this 🙏

You can find the char count of the current note in the right sidebar, looks like this:

<img width="279" alt="CleanShot 2022-12-10 at 10 33 25@2x" src="https://user-images.githubusercontent.com/184170/206841303-a4f08a5a-f608-4ea8-bff3-bf4eb3ea1bce.png">

You can open the right sidebar from the button at the top-right corner:

<img width="136" alt="CleanShot 2022-12-10 at 10 31 56@2x" src="https://user-images.githubusercontent.com/184170/206841256-5f0378f6-aab4-4c1c-b7d7-66bd21d43205.png">

You can also open it from the `Command Palette` (⇧⌘P) and even assign a shortcut from `Preferences` (⌘,).

Perhaps we should also make it possible to configure what `word count` shows so that you can see char count without having to open the right sidebar.
