### ISSUE TITLE
How often and how do you get updates for Nota app?

### ISSUE THREAD

**Issue by evaldsurtans** [notaapp/nota#131]

**Comment by astoilkov** [comment]
Updates are downloaded automatically. You will see a dialog box when a new update is ready for installation.

The time between updates is different every time. The current release we are preparing is taking a lot of time because we are doing something hard and can't figure out the right design. There have been times we've released every two weeks. Most commonly we release once a month.

For more information, you can see previous release dates [here](https://nota.md/changelog.html).

**Comment by evaldsurtans** [comment]
Last update in 15 September 2021 ? :)

**Comment by astoilkov** [comment]
Yes, we have been working on a big update that, admittedly, has been taking us too much. The good news is that the new update includes over 20 new features (not counting improvements and bug fixes).

**Comment by astoilkov** [comment]
The new release is now available to all users. Sorry for the big gap between these two updates. That won't probably happen again. In a few weeks, we will release a new (again big) update.

Closing this issue now.
