### ISSUE TITLE
Do not include non-workspace links.

### ISSUE THREAD

**Issue by Overload119** [notaapp/nota#60]
I have 2 workspaces, 1 work and 1 personal.

In the "work" workspace I accidentally opened a link in the Personal.
(This is a document called Session Log).

![image](https://user-images.githubusercontent.com/1012072/121236718-1aa42700-c84b-11eb-97ac-1bf8ea7925f4.png)

Now any time I search for Session Log it shows me the Personal one within the Work workspace. 
This is a bit of a nuisance. I think it would be better to scope files searches within the Workspace you are currently on.

**Comment by astoilkov** [comment]
Quick question. I thought of a way to improve the current behavior — move external files to the bottom of the search. This will be an improvement if your problem is that you accidentally open the wrong file. However, it won't be a solution if the cause is different. Can you share why you don't want files to appear?

Personally, I don't like the current behavior because some personal information may show up while showing something to a colleague at work for example.

**Comment by Overload119** [comment]
I think it's clutter. 
I don't see why I would want to view an external file from my workspace frequently - it defeats the point of the workspace. If I accidentally added a file, I think while it's open as a tab you can keep it searched otherwise it should not appear.

**Comment by Overload119** [comment]
In my use case above I will never click on the one outside my workspace. It will always be there though and that's a waste of UI space. 

There could be an option to "forget this file" but I feel it's not worth it.

**Comment by astoilkov** [comment]
I've made external files not available in files popup and editor completions. It's possible we find a better solution in the future, but for now, we prefer to make it simpler by default.

Note that the same problem exists in the Workspaces popup where, if you open a workspace, you can never remove it.

**Comment by astoilkov** [comment]
We changed this behavior and now we don't include external files in the Files dialog.

Closing this.
